package main

import (
	"flag"
	"fmt"
	"log"
	"os"

	pptagent "github.com/pandorafms/pandoraplugintools-go/pkg/agent"
	pptmodule "github.com/pandorafms/pandoraplugintools-go/pkg/module"
)

func main() {
	log.SetFlags(0)

	if len(os.Args) < 2 {
		printUsage()
		return
	}

	switch os.Args[1] {
	case "example-xml":
		runExampleXML(os.Args[2:])
	case "help", "-h", "--help":
		printUsage()
	default:
		log.Fatalf("unknown command %q\n\n", os.Args[1])
	}
}

func printUsage() {
	fmt.Println("pandoraplugintools-go CLI scaffold")
	fmt.Println()
	fmt.Println("Available commands:")
	fmt.Println("  example-xml   Render a sample Pandora XML payload using the library")
	fmt.Println("  help          Show this help")
}

func runExampleXML(args []string) {
	fs := flag.NewFlagSet("example-xml", flag.ExitOnError)
	agentName := fs.String("agent", "demo-agent", "Agent name")
	moduleName := fs.String("module", "CPU usage", "Module name")
	moduleValue := fs.String("value", "10", "Module value")
	fs.Parse(args)

	ag, err := pptagent.New(pptagent.Config{AgentName: *agentName, AgentAlias: *agentName})
	if err != nil {
		log.Fatal(err)
	}

	mod, err := pptmodule.New(pptmodule.Config{
		Name:           *moduleName,
		Type:           "generic_data",
		Value:          *moduleValue,
		Description:    "Example module generated by the CLI scaffold",
		Unit:           "%",
		ModuleGroup:    "system",
		MinWarning:     "60",
		MaxCritical:    "95",
		AlertTemplates: []string{"cpu-warning"},
	})
	if err != nil {
		log.Fatal(err)
	}

	if err := ag.AddModule(mod); err != nil {
		log.Fatal(err)
	}

	xmlData, err := ag.XML()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Print(string(xmlData))
}
